---
title: "NS_ch5"
adapted from: "Maria Izabel Cavassim Alves"
curated by: "Calin Pantea"
date: "10/6/2017 - 05/10/2023"
output: html_document
---

## Chapter 5: Inferring Population History and Demography

```{r}
#Exercise 5.1
Time = 2*FST[1]/(1- FST[1])

pop1 = c(12, 22, 6)
names(pop1) = c('AA', 'Aa', 'aa')
pop2 = c(32, 6, 2)
names(pop2) = c('AA', 'Aa', 'aa')
pop_new2 = rbind(pop1, pop2)

FST = wahlund_effect(pop_new2)


# In coalescent time units
Time = 2*FST[1]/(1- FST[1])
two_N = 10000
r_year = 5
# In years time
Time*two_N*r_year
```

```{r}
# Exercise 5.4

theta = seq(from = 0, to = 20)
Pr = ((1/(1 + theta))*(theta/(1 + theta))^4)
names(Pr) = theta

#These are all the probabilities for the given thetas
plot(theta, Pr, type = 'l', ylab = 'Likelihood of theta')

# Theta estimate of watterson
n = 2
d = 4
theta_w = 2*d/n*(n- 1) # number of differences divided by the number of combinations
abline(v = theta_w, col = 'red', lty = 2)
max_likelihood = max(Pr)
abline(h = max_likelihood, col = 'black', lty = 2)

```

```{r}
# Exercise 5.5
# The posterior probability of observing genotype aa is:
# probability of observing genotype aa given it comes from pop1*probability of being in this region / probability of observing genotype aa given it #comes from pop1*probability of being in this region + probability of observing genotype aa given it comes from pop2*probability of being in this region

# 5.5 a
pop_new2

p1 = p2 = 0.5
faa_1 = pop_new2[1,3]
faa_2 = pop_new2[2,3]
(pos1 = faa_1*p1/(faa_1*p1 + faa_2*p2))

# 5.5 b
p1 = 0.1
p2 = 0.9
(pos2 = faa_1*p1/(faa_1*p1 + faa_2*p2))
```

```{r}

```


```{r}
```